### ISSUE TITLE
Test Suite failing

### ISSUE THREAD

**Issue by Cameron-Janrain** [janrain/janrain-python-api#5]
6/8 tests failed

```sh
running test
running egg_info
writing janrain_python_api.egg-info/PKG-INFO
writing namespace_packages to janrain_python_api.egg-info/namespace_packages.txt
writing top-level names to janrain_python_api.egg-info/top_level.txt
writing dependency_links to janrain_python_api.egg-info/dependency_links.txt
reading manifest file 'janrain_python_api.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'janrain_python_api.egg-info/SOURCES.txt'
running build_ext
test_api_encode (janrain.capture.test.test_api.TestApi) ... ERROR
test_api_object (janrain.capture.test.test_api.TestApi) ... ERROR
test_clusters (janrain.capture.test.test_config.TestConfig) ... ok
test_defaults (janrain.capture.test.test_config.TestConfig) ... ok
test_resolving_keys (janrain.capture.test.test_config.TestConfig) ... ERROR
test_api_response_error (janrain.capture.test.test_errors.TestErrors) ... ERROR
test_invalid_api_call_error (janrain.capture.test.test_errors.TestErrors) ... ERROR
test_invalid_url_error (janrain.capture.test.test_errors.TestErrors) ... ERROR

======================================================================
ERROR: test_api_encode (janrain.capture.test.test_api.TestApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/test/test_api.py", line 10, in setUp
    client = config.unittest_client()
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/config.py", line 59, in unittest_client
    raise JanrainConfigError(message)
JanrainConfigError: Could not find key 'unittest_client' in '/Users/cameron/.janrain-capture'.

======================================================================
ERROR: test_api_object (janrain.capture.test.test_api.TestApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/test/test_api.py", line 10, in setUp
    client = config.unittest_client()
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/config.py", line 59, in unittest_client
    raise JanrainConfigError(message)
JanrainConfigError: Could not find key 'unittest_client' in '/Users/cameron/.janrain-capture'.

======================================================================
ERROR: test_resolving_keys (janrain.capture.test.test_config.TestConfig)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/test/test_config.py", line 41, in test_resolving_keys
    config.get_settings_at_path("foo.bar")
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/config.py", line 25, in get_settings_at_path
    .format(dot_path, get_config_file()))
JanrainConfigError: Could not find key 'foo.bar' in '/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/test/janrain-config'.

======================================================================
ERROR: test_api_response_error (janrain.capture.test.test_errors.TestErrors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/test/test_errors.py", line 7, in setUp
    client = config.unittest_client()
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/config.py", line 59, in unittest_client
    raise JanrainConfigError(message)
JanrainConfigError: Could not find key 'unittest_client' in '/Users/cameron/.janrain-capture'.

======================================================================
ERROR: test_invalid_api_call_error (janrain.capture.test.test_errors.TestErrors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/test/test_errors.py", line 7, in setUp
    client = config.unittest_client()
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/config.py", line 59, in unittest_client
    raise JanrainConfigError(message)
JanrainConfigError: Could not find key 'unittest_client' in '/Users/cameron/.janrain-capture'.

======================================================================
ERROR: test_invalid_url_error (janrain.capture.test.test_errors.TestErrors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/test/test_errors.py", line 7, in setUp
    client = config.unittest_client()
  File "/Users/cameron/Repos/Janrain/janrain-python-api/janrain/capture/config.py", line 59, in unittest_client
    raise JanrainConfigError(message)
JanrainConfigError: Could not find key 'unittest_client' in '/Users/cameron/.janrain-capture'.

----------------------------------------------------------------------
Ran 8 tests in 0.053s

FAILED (errors=6)
```

**Comment by ebeesonjanrain** [comment]
The tests require clients.janrain-capture-api-unittest be configured for a real Capture app.
